export const textArr = {
  acte1: [
    ["hi", "i'm samuals", "my life is interesting", "hi", "yo", '<span class="emphasis">yey</span>'],
    ["yey", 'it\'s <span class="emphasis">done</span>', "yes", "hhum"],
  ],

  // acte1: [
  //   [
  //     "il était une fois",
  //     "un groupe de personnes",
  //     "qui avaient tous et toutes un rapport différent aux ordinateurs.",
  //     "au sein de ce groupe",
  //     "certaines personnes aimaient les ordinateurs",
  //     "parce qu'elles aimaient le bleu vidéo",
  //     "ou parce qu'elles aimaient les jeux vidéo",
  //     "d'autres personnes n'aimaient pas les ordinateurs",
  //     "parce qu'un ordinateur leur avait fait du mal",
  //     "d'autres personnes encore prétendaient ne pas avoir d'opinion au sujet des ordinateurs",
  //     "parce qu'elles aimaient se voir comme des personnes restant au dessus de la mêlée.",
  //     "Quoi qu'il en soit",
  //     "toutes ces personnes sans exception",
  //     "avaient déjà vu un ordinateur.",
  //     "elles étaient absolument entourées d'ordinateurs.",
  //     "cernées par les ordinateurs.",
  //     "bercées par les ordinateurs.",
  //     "depuis la naissance,",
  //     "parce qu'un ordinateur veillait sur leur rythme cardiaque",
  //     "jusqu'au tombeau",
  //     "parce que quelqu'un utilisera inévitablement un smartphone pour dire l'oraison funèbre.",
  //     "Presque toutes ces personnes",
  //     "possédaient un ou plusieurs ordinateurs",
  //     "ces personnes en avaient d'ailleurs actuellement un dans la poche ou pas loin",
  //     "en mode silencieux bien naturellement",
  //     "Et toutes",
  //     "ces personnes",
  //     "ou presque toutes",
  //     "avaient déjà vu une souris d'ordinateur",
  //     "comme celles qu'il y avait dans la salle",
  //     "suspendues au dossier du siège devant elles.",
  //     "par moi",
  //     "pour nous",
  //     "c'est alors qu'une personne",
  //     "parmi nous",
  //     "s'est reconnue.",
  //     "cette personne,",
  //     "qui s'était toujours considérée comme une personne aventureuse,",
  //     "exploratrice, ambitieuse, jamais satisfaite du statut quo, impatiente, curieuse, méthodique, finalement sans peur et toujours prête à se mettre en danger, en danger mortel,",
  //     "n'ayant pas peur de l'anéantissement intellectuel ou de la dissolution de sa personnalité face à l'adversité, face à la torture même, n'ayant pas peur de se désintégrer dans l'immensité du néant, pour qui les milliard d'années de vide; c'est à dire, la quantité infinie de vide avant nous et la quantité infinie de vide après nous n'inspirait aucun vertige, que ce soit par manque de lucidité d'ailleurs, ou pour des raisons métaphysiques, peu importe, elle a pas peur de la mort on vous dit.",
  //     "cette personne,",
  //     "rare,",
  //     "décida de prendre la souris devant elle",
  //     "de la disposer sur ses genoux",
  //     "et de cliquer sur le bouton",
  //     "droit",
  //     "de sa souris.",
  //   ],
  // ],
  // acte1: [
  //   [
  //     "Il était une fois l'histoire d'un groupe de personnes.",
  //     "Ces personnes, curieuses et entreprenantes, s'étaient rassemblées dans une salle.",
  //     "Se fiant à des informations glanées sur internet, ou déposées dans leurs oreilles par un pair, elles avaient décidé de s'enfermer ensemble volontairement.",
  //     "Pour vivre une expérience à mi-chemin entre le rituel et le divertissement.",
  //     "Ces personnes n'avaient pas peur.",
  //     "Non vraiment, c'étaient des personnes vraiment... Braves.",
  //     "Néanmoins, il se passait une chose inhabituelle.",
  //     "Contrairement à ce qui se passait d'habitude quand le groupe de personnes s'enfermait volontairement dans une salle, le plateau de théâtre était resté vide.",
  //     "Habituellement, le groupe de personnes était récompensé assez rapidement après s'être assis dans la salle.",
  //     "Récompensé, parce qu'elles avaient dépassé leur peur de s'enfermer avec des inconnu.e.s.",
  //     "En sachant très bien qu'elles allaient devoir, une heure durant, faire passer l'air exhalé par de nombreux autres poumons à l'intérieur de leurs propres poumons.",
  //     "Dont des poumons citadins tout jaunes et flétris par le tabac, on le sait parce qu'on a vu des images de vos poumons sur les paquets de cigarettes.",
  //   ],
  //   [
  //     "Donc imaginez un peu l'air qui sort de ces poumons, ça peut pas être un air frais de la montagne qui sent bon l'épicéa n'est-ce-pas?",
  //     "Bon en même temps, vous avez raison, les poumons de citadins qui ne fument pas sont bien flétris aussi.",
  //     "Et encore on est pas à plaindre hein, imaginez un peu comment ils étaient les poumons des gens en 1850 en Angleterre. (tousse)",
  //     "Normalement, comme je disais (renifle), pardon, (se mouche), le groupe de personnes était récompensé d'avoir sacrifié une soirée entière de leur vie.",
  //     "Où iels auraient pu jouer à Fortnite, à Roblox, à Counter-Strike 2, à Elden Ring, à Geoguessr, à The Witcher 3 : Wild Hunt – Édition Jeu de l'Année.",
  //     "Au Seigneur des Anneaux : La Bataille pour la Terre du Milieu II – L'Avènement du Roi-Sorcier.",
  //     "À Dragon Quest Heroes : Le Mal qui menace l'Arbre du Monde, à Dragon Quest III : et la légende fut, trois petits points.",
  //     "À Dragon Quest VIII : Le ciel, la mer, la terre et la princesse maudite.",
  //     "Leur récompense, c'était la présence d'une personne réelle, devant eux, en chair et en os, respirant, parlant.",
  //     "Avec un cœur, des cordes vocales, enfin, le plus souvent avec des cordes vocales, et toutes choses égales par ailleurs, avec des poumons.",
  //     "Mais là, personne. En tout cas personne sur le plateau.",
  //     "Pourquoi? Comment était-ce possible de refuser au groupe de personnes courageuses cet égard, ce qui était tout de même la moindre des choses.",
  //     "Est-ce que le théâtre se foutait de leur gueule en fait? Non parce que.",
  //     "Ou alors... Est-ce que l'artiste... c'est l'artiste qui s'était foutu de la gueule du théâtre.",
  //     "Il avait vendu un Chekhov au théâtre en se disant allez ça passe et puis on verra ce que je fais quand j'aurai l'argent.",
  //     "Ou alors, c'était une personne travaillant à la programmation du théâtre qui voulait saboter de l'intérieur le fonctionnement du théâtre.",
  //     "Pour que le directeur soit décrédibilisé auprès de ses tutelles, afin de prendre sa place quand il se ferait éjecter.",
  //     "Ou alors, c'était un bot, un bot russe, qui avait envoyé un message de phishing au théâtre.",
  //     "Proposant de monter un Chekhov (un compatriote), le théâtre était tombé dans le panneau.",
  //     "La coprod avait servi à financer la guerre en Ukraine, pendant que le bot envoyait ce texte au théâtre pour camoufler l'embrouille.",
  //     "Mais le groupe de personnes, qui n'étaient pas dépourvues de sens de l'observation, avaient remarqué qu'il y avait des souris d'ordinateur disposées dans les gradins.",
  //     "C'était bien la preuve que l'artiste, ou le bot russe, avait prévu qu'il se passe quelque chose ici.",
  //     "Ou alors c'était par pur sadisme, et en fait les souris n'étaient même pas branchées.",
  //     "C'est alors (pause) qu'une personne dans le groupe (pause), qui s'était d'ailleurs toujours vue comme une personne aventureuse, exploratrice, ambitieuse.",
  //     "Jamais satisfaite du statut quo, impatiente, curieuse, méthodique, finalement sans peur et toujours prête à se mettre en danger, en danger mortel.",
  //     "N'ayant pas peur de l'anéantissement intellectuel ou de la dissolution de sa personnalité face à l'adversité, face à la torture même.",
  //     "N'ayant pas peur de se désintégrer dans l'immensité du néant.",
  //     "Pour qui les milliards d'années de vide; c'est-à-dire, la quantité infinie de vide avant nous et la quantité infinie de vide après nous n'inspirait aucun vertige.",
  //     "Que ce soit par manque de lucidité d'ailleurs, ou pour des raisons métaphysiques, peu importe, elle a pas peur de la mort on vous dit.",
  //     "Cette personne, rare, décida de toucher sa souris d'ordinateur et de cliquer sur le bouton droit de la souris.",
  //   ],
  // ],
}
